### ISSUE TITLE
Missing Controller

### ISSUE THREAD

**Issue by davidheart24** [QueenCityCodeFactory/CakeSpreadsheet#1]
Hello,
I follow the configuration, but Im getting this error :  
Missing Controller
Users.xlsxController could not be found.

**Comment by davidheart24** [comment]
Check my gist
https://gist.github.com/davidheart24/fb70aca831c6bb38c717c934f30fde9f

**Comment by Matthew-Benson** [comment]
Looks like when defining your routes you don't have your route builder set up with the extension you're using in the Html helper. You should have a line like:

`$builder->extensions(['xlsx']);`

**Comment by davidheart24** [comment]
Thanks bro - I added this to my builder  $builder->setExtensions(['xlsx']);
working now.
